import logging

import duckdb
from pydantic import BaseModel, Field
from pydantic_ai import Agent, ModelRetry, RunContext
from sqlglot import ParseError

from stocksense.ai import setup_phoenix_tracing
from stocksense.ai.skills.context import StockDBContextDependency
from stocksense.ai.skills.tools.sql import (
    SQLQueryValidator,
    check_sql_query_returns_data,
)
from stocksense.ai.utils import fetch_system_prompt, fetch_user_prompt, get_model

logger = logging.getLogger("stocksense")

# Phoenix setup
setup_phoenix_tracing()


class TextToSQLOutput(BaseModel):
    sql_query: str = Field(
        ..., description="Generated SQL query based on the user's request"
    )


async def text_to_sql(
    model_name: str,
    api_key: str,
    base_url: str | None = None,
) -> Agent[StockDBContextDependency, TextToSQLOutput]:
    # initialize the agent
    agent: Agent[StockDBContextDependency, TextToSQLOutput] = Agent(
        model=get_model(model_name, api_key, base_url),
        name="text-to-sql",
        deps_type=StockDBContextDependency,
        output_type=TextToSQLOutput,
        instrument=True,
    )

    @agent.system_prompt
    async def add_system_prompt(
        ctx: RunContext[StockDBContextDependency],
    ) -> str:
        # NOTE - System prompt is static and does not need to be formatted with variables
        return await fetch_system_prompt(
            prompt_identifier="text-to-sql",
            variables={"table_name": "", "columns_to_used": ""},
        )

    # Adding instruction to the agent
    @agent.instructions
    async def adding_tasks(ctx: RunContext[StockDBContextDependency]) -> str:
        # NOTE - Instructions are formatted with context variables
        return await fetch_user_prompt(
            prompt_identifier="text-to-sql",
            variables={
                "table_name": ctx.deps.table_name,
                "columns_to_used": ", ".join(ctx.deps.columns),
            },
        )

    @agent.tool
    def verify_duckdb_sql_query(
        ctx: RunContext[StockDBContextDependency], query: str
    ) -> str:
        """Use this tool to perform various validation checks. Bellow checks are available:
        1. Syntax wrt to DuckDB
        2. Table name

        Parameters
        ----------
        query : str
            SQL query to perform syntax validation on

        Returns
        -------
        str
            validated sql query

        Raises
        ------
        ModelRetry
            letting the LLM Model know whats the issue is
        """
        logger.debug(f"Validating SQL query: {query}")
        validator = SQLQueryValidator(query=query)
        try:
            return (
                validator.verify_syntax()
                # TODO - improved column verification logic
                # .verify_columns(ctx.deps.columns)
                .verify_table_name(ctx.deps.table_name)
                .run(optimize=False)
            )
        except (ValueError, ParseError) as e:
            logger.warning(f"SQL query validation error: {e}", exc_info=True)
            raise ModelRetry(f"Invalid SQL query: {e}")

    @agent.tool
    def verify_duckdb_sql_query_returns_data(
        ctx: RunContext[StockDBContextDependency], query: str
    ) -> bool:
        """Use this tool to check if the SQL query returns any data. This can be used to further validate the SQL query generated by the model.

        Parameters
        ----------
        query : str
            SQL query to be executed in the database to check if it returns any data

        Returns
        -------
        bool
            True if the query returns data, False otherwise

        Raises
        ------
        ModelRetry
            letting the LLM Model know whats the issue is
        """
        logger.debug(f"Checking if SQL query returns data: {query}")
        try:
            if not check_sql_query_returns_data(ctx.deps.history_data, query):
                raise ModelRetry(
                    "The SQL query is valid but returns no data. Please modify the query to return some data."
                )
            return True
        except (duckdb.Error, ParseError) as e:
            logger.warning(f"Error executing SQL query: {e}", exc_info=True)
            raise ModelRetry(f"Error executing SQL query: {e}")

    # returning the initialized agent at the end
    return agent
