name: Stock-Research-Assistant
services:
  # 1. Snapshot Data Initialization Service
  init_snapshot:
    image: akashdesarda/srp-snapshot-data:latest
    volumes:
      - shared-data:/snapshot
      - ./config.toml:/tmp/config.toml
    command:
      [
        "/bin/sh",
        "-c",
        "/snapshot_data_decompress.sh && cp /tmp/config.toml /snapshot/config.toml",
      ]
  # 2. Stock Database API Service
  stockdb-api:
    build:
      context: ./stockdb
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - shared-data:/stockdb/shared
    environment:
      CONFIG_FILE: /stockdb/shared/config.toml
      DOCKER_CONTAINER: "true" # Explicit Docker environment flag
    tty: true

volumes:
  shared-data:
    name: "sra-shared-data"
