name: Build and Push Docker Images
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare image tag
        run: echo "IMAGE_TAG=$(date -u +'%Y%m%d%H%M')" >> $GITHUB_ENV
      - name: Build and push stockdb
        uses: docker/build-push-action@v5
        with:
          context: ./stockdb
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/srp-stockdb-api:latest
            ghcr.io/${{ github.repository_owner }}/srp-stockdb-api:${{ env.IMAGE_TAG }}
      - name: Build and push snapshot
        uses: docker/build-push-action@v5
        with:
          context: ./snapshot
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/srp-snapshot-data:latest
            ghcr.io/${{ github.repository_owner }}/srp-snapshot-data:${{ env.IMAGE_TAG }}
